language: node_js

node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"

notifications:
  email: false

  irc:
    channels:
      - "chat.freenode.net#jitsu"
    on_success: change
    on_failure: change

